#pragma once

#undef VENDOR_ID
#undef PRODUCT_ID

#define VENDOR_ID      0x1209
#define PRODUCT_ID     0x0001

#define DYNAMIC_MACRO_NO_NESTING

#undef USB_POLLING_INTERVAL_MS
#define USB_POLLING_INTERVAL_MS 1
