#pragma once

#undef VENDOR_ID
#undef PRODUCT_ID

#define VENDOR_ID      0x1209
#define PRODUCT_ID     0x0003

#undef RGBLIGHT_ANIMATIONS
#undef RGBLIGHT_DEFAULT_MODE
#define RGBLIGHT_LAYERS
#define RGBLIGHT_LAYER_BLINK
#define RGBLIGHT_LAYERS_OVERRIDE_RGB_OFF
